language: cpp
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages: &common_deps
      - antlr3
      - cmake
      - cxxtest
      - junit4
      - libantlr3c-dev
      - libcln-dev
      - libgmp-dev
      - libhamcrest-java
      - openjdk-8-jdk
      - swig3.0
      - python3
      - python3-pip
      - python3-setuptools
      - ruby
      - libfl-dev

jobs:
  include:
    - os: osx
      osx_image: xcode9.2

script:
  # brew sometimes fails on something even after a successful python installation
  # we don't want the build to fail
  - ./scripts/travis-setup-osx-python.sh || true
  # - sudo python3 -m pip install Cython==0.29 --install-option="--no-cython-compile"
  # - sudo python3 -m pip install pytest
  # - ./travis-scripts/setup-msat.sh --auto-yes
  - ./contrib/setup-smt-switch.sh
  # - sudo python3 -m pip install -e ./deps/smt-switch/build/python
  - ./contrib/setup-btor2tools.sh
  - ./contrib/setup-bison.sh
  - ./configure.sh --debug
  # - ./configure.sh --with-msat --python --debug
  # - cd build && make -j2 && make test && cd ../
  # - sudo python3 -m pip install -e ./build/python
  # - pytest ./tests
